# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-breakout"
BBFILE_PATTERN_meta-breakout = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-breakout = "6"

LAYERDEPENDS_meta-breakout = "core"
LAYERSERIES_COMPAT_meta-breakout = "scarthgap"
